PRODUCT_VERSION_MAJOR = 6.0
PRODUCT_VERSION_MINOR = Alpha
PRODUCT_VERSION_MAINTENANCE = 0.1


ifndef ONEROM_BUILD_TYPE
    ONEROM_BUILD_TYPE := HOMEMADE
    ONEROM_POSTFIX := -$(shell date +"%Y%m%d-%H%M")
endif


# Set all versions
ONEROM_VERSION := OneRom-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(ONEROM_BUILD_TYPE)$(ONEROM_POSTFIX)
ONEROM_MOD_VERSION := OneRom-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.onerom.version=$(ONEROM_VERSION) \
    ro.modversion=$(ONEROM_MOD_VERSION) \
    ro.onerom.buildtype=$(ONEROM_BUILD_TYPE)
